name: 'Xcode Simulator Selector'
author: 'Steffan Andrews'
description: 'Dynamically find the best available Xcode device simulator.'
inputs:
  workspace-path:
    description: 'Relative path to the Xcode workspace. If the target is a Swift Package that exists in the root of the repository, omit this variable.'
    required: false
  scheme:
    description: 'Xcode scheme name that will be used when enumerating available device simulators.'
    required: true
  target:
    description: 'Platform (iOS, tvOS, watchOS, visionOS) device (iphone, ipad, watch, appletv, visionpro). See README for more options.'
    required: true
  os-version:
    description: 'Platform OS version regular expression. (Optional)'
    required: false
outputs:
  id:
    description: "Simulator ID"
    value: ${{ steps.id-finder.outputs.id }}
runs:
  using: "composite"
  steps:
    - name: Find Simulator ID
      id: id-finder
      run: scripts/id.sh
      shell: bash
      env:
        INPUT_WORKSPACEPATH: ${{ inputs.workspace-path }}
        INPUT_SCHEME: ${{ inputs.scheme }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_OSVERSION: ${{ inputs.os-version }}
branding:
  icon: 'code'
  color: 'blue'
